# Generated by Django 4.2.8 on 2023-12-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
