# Generated by Django 4.2.8 on 2023-12-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_gym_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='gym',
            name='stripeid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gym',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
