# Generated by Django 4.2.8 on 2023-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_member_alter_gym_managers_gym_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='gym',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
