# Generated by Django 4.2.8 on 2023-12-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_rename_name_gym_firstname_gym_lastname_gym_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
